export const Images = {
  GITHUB:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/1024px-Octicons-mark-github.svg.png',
  LOG_OUT:
    'https://cdn1.iconfinder.com/data/icons/essentials-pack/96/logout_close_sign_out_exit_access-512.png',
  MAIN_LOGO:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/bmart-logo.png',
  EMPTY_CART:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/empty.png',
  SMALL_BANNER1:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/small_1.jpg',
  SMALL_BANNER2:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/small_2.jpg',
  SMALL_BANNER3:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/small_3.jpg',
  SMALL_BANNER4:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/small_4.jpg',
  SMALL_BANNER5:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/small_5.gif',
  CART_ICON_MINT:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/cart_img_mint.png',
  CART_ICON_WHITE:
    'https://bmart-9.s3.ap-northeast-2.amazonaws.com/public/cart_img_white.png',
};
